# Generated by Django 5.0 on 2023-12-30 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersDetails', '0001_initial'),
        ('payments', '0002_paymentwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainPaymentTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('type', models.CharField(default='pending', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user_transactions', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'main_payment_transactions',
                'managed': True,
            },
        ),
    ]
