# Generated by Django 5.0 on 2024-01-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mainpaymenttransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfSaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='static/')),
            ],
            options={
                'db_table': 'main_payment_transdsaactions',
                'managed': True,
            },
        ),
    ]
