# Generated by Django 5.0 on 2024-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_pdfsaver'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwithdrawal',
            name='bank_account',
            field=models.TextField(null=True),
        ),
    ]
