# Generated by Django 5.0 on 2024-01-10 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersDetails', '0002_invoicestable_created_at_alter_invoicestable_file'),
        ('payments', '0005_paymentwithdrawal_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='status',
            field=models.CharField(default='completed', max_length=15),
        ),
        migrations.CreateModel(
            name='TokenGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_generator', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('status', models.CharField(default='unclaimed', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_generated_token', to='UsersDetails.usersdetails')),
                ('user_redeemed', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_redeemed_token', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'token_payments',
                'managed': True,
            },
        ),
    ]
