# Generated by Django 5.0 on 2023-12-28 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('file', models.FileField(upload_to='static/pdfs/')),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='user_invoice', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'invoices_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, null=True)),
                ('company_address', models.TextField(null=True)),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'customer_details',
                'managed': True,
            },
        ),
    ]
