# Generated by Django 5.0 on 2024-01-03 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestable',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoicestable',
            name='file',
            field=models.TextField(),
        ),
    ]
