# Generated by Django 5.0 on 2023-12-28 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_unique_id', models.CharField(max_length=10, null=True)),
                ('photo_url', models.FileField(upload_to='static/products-photos/')),
                ('product_name', models.CharField(max_length=30, null=True)),
                ('product_drop_shipping_url', models.TextField(null=True)),
                ('quoted_price', models.IntegerField(null=True)),
                ('status', models.CharField(default='quotation pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'products_customer',
                'managed': True,
            },
        ),
    ]
