# Generated by Django 5.0 on 2024-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscustomer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productscustomer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
