# Generated by Django 5.0 on 2024-01-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0002_productscustomer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscustomer',
            name='asked_price',
            field=models.IntegerField(null=True),
        ),
    ]
