# Generated by Django 5.0 on 2023-12-28 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField(null=True)),
                ('request_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='user_coins_request', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'coin_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoinsSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to='UsersDetails.usersdetails')),
            ],
            options={
                'db_table': 'coin_systems',
                'managed': True,
            },
        ),
    ]
