# Generated by Django 5.0 on 2023-12-28 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('phone_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pending_query',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ordersCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_id', models.CharField(max_length=10, null=True)),
                ('customer_address', models.TextField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(default='order placed', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_obj', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_obj', to='productManagement.productscustomer')),
            ],
            options={
                'db_table': 'orders_created',
                'managed': True,
            },
        ),
    ]
