# Generated by Django 5.0 on 2023-12-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderscreated',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
