# Generated by Django 5.0 on 2024-01-08 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersDetails', '0002_invoicestable_created_at_alter_invoicestable_file'),
        ('orderManagement', '0004_lineordercreated_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscreated',
            name='user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_order', to='UsersDetails.usersdetails'),
        ),
        migrations.AlterField(
            model_name='lineordercreated',
            name='status',
            field=models.CharField(default='draft', max_length=15),
        ),
    ]
