# Generated by Django 5.0 on 2024-01-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0005_orderscreated_user_alter_lineordercreated_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineordercreated',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
